server:
  port: 8764

spring:
  application:
    name: SERVICE-RIBBON

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream



