server:
  port: 8998

spring:
  application:
    name: SERVICE-HI
  zipkin:
    base-url: http://localhost:9411

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:7761/eureka/


